### PR TITLE
Provide RenderParams for the stories

### PR DESCRIPTION
**Pull request by vvsevolodovich**
In order to configure how the widgets are displayed inside the Rows RenderParams are introduced

### CODE REVIEW

**Comment by vvsevolodovich** [comment]
Fixes #11

**Comment by vvsevolodovich** [comment]
@ilikerobots  did you have a chance to take a look?

**Comment by ilikerobots** [comment]
> @ilikerobots did you have a chance to take a look?

Yes, I left a comment here. https://github.com/ilikerobots/storyboard/issues/11

Take a look and let me know your thoughts please.

**Comment by ilikerobots** [comment]
merged #12 instead, but thanks much regardless @vlivanov

**Pull request closed without merging**
